### ISSUE TITLE
Can I translate your article about "Transducers Explained" into Chinese?

### ISSUE THREAD

**Issue by adispring** [kevinbeaty/transducers-explained#1]
Hi, @kevinbeaty , I have just read about "Transducers Explained" in your blog. You explain transducer in an accessible and engaging way. There are few aritcles about transduce, and these articles don't explain `transduce` clearly. 
So can I translate the articles? this will help more people to understand `Transduce`.

**Comment by kevinbeaty** [comment]
Thnaks @adispring .   Sounds good to me as long as you credit the original in your translation.  Note that there is an existing translation here for the first article: https://987.tw/2015/03/22/xi-shuo-transducers-part-1/

**Comment by adispring** [comment]
I have just saw the translation, this guy's translation is Traditional Chinese used in Taiwan, but in Mainland of China ,we use Simple Chinese. There are some difference between Traditional and Simple Chinese, such as word\syntax etc.

**Comment by kevinbeaty** [comment]
Thanks for taking a look.  I just thought I'd point it out.   A translation to Simple Chinese would be awesome. 

Feel free to translate as long as you reference the original.  Also feel free to make a PR here with the translation in the README, and add a comment to with a link to your translation on the post.

Thanks again!

**Comment by adispring** [comment]
Ok, I will translate `Transducers Explained: Part 1` this week, and let my company's colleagues help to translate and review it.
After complete the translation, I then will make a pr here and give the link to the post.

And Thank you for authorizing me to translate your article, and for explaining transducer so clearly!

**Comment by adispring** [comment]
Hi, @kevinbeaty ,I've just finished translating "Transducers Explained: Part 1", this is the website: https://adispring.github.io/2016/10/24/Transducers-Explained-Part-1/

I add some note in the article, and insert three pictures to explain `reduce` & `transducer` more directly. and use some ES6 syntax.

You can review the translation. and give some advise to me to optimize it. If everything is ok, then I'll make a pr to this repository.

**Comment by adispring** [comment]
I plan to translate [Transducers Explained: Pipelines](http://simplectic.com/blog/2014/transducers-explained-pipelines/) in the next two weeks.
